# GitHub Actions example: build image, run scanner, upload SARIF
# Replace <IMAGE_NAME> with your built image ref
name: Scan
on: push
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t app:latest .

      - name: Run container scanner
        run: |
          docker run --rm -v $PWD/reports:/reports \
            scanner:latest scan --image app:latest --output-dir /reports --format sarif,markdown

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/report.sarif

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan-reports
          path: reports/
